In [4]:
import pandas as pd

In [36]:

df = pd.read_pickle('Str_Bench_RET.pkl')
df

           Date  Strat_Ret  Bench_Ret
0    2013-05-23  -0.004857  -0.003551
1    2013-05-24  -0.002945  -0.001320
2    2013-05-28   0.006070   0.007137
3    2013-05-29  -0.013526  -0.007611
4    2013-05-30   0.006074   0.004364
...         ...        ...        ...
3227 2026-03-24   0.018806  -0.000862
3228 2026-03-25  -0.010812   0.003548
3229 2026-03-26  -0.010563  -0.037594
3230 2026-03-27   0.003166   0.007888
3231 2026-03-30   0.007897   0.003793

[3232 rows x 3 columns]

In [23]:
import pandas as pd
df = pd.read_pickle('full_backtest_and_real_time.pkl')
df

            Full_Backtest  Real_Time
Date
2013-05-28       0.021072        NaN
2013-05-29      -0.018593        NaN
2013-05-30      -0.000057        NaN
2013-05-31      -0.004204        NaN
2013-06-03      -0.011822        NaN
...                   ...        ...
2026-04-02      -0.009726   0.013447
2026-04-06       0.013266   0.001199
2026-04-07       0.001241   0.032104
2026-04-08       0.032099  -0.000135
2026-04-09       0.000097   0.010476

[3237 rows x 2 columns]

In [39]:
df.dropna().shape

(42, 2)