In [4]:
import pandas as pd

In [31]:

df = pd.read_pickle('Str_Bench_RET.pkl')
df

           Date  Strat_Ret  Bench_Ret
0    2013-05-23  -0.004857  -0.003551
1    2013-05-24  -0.002945  -0.001320
2    2013-05-28   0.006070   0.007137
3    2013-05-29  -0.013526  -0.007611
4    2013-05-30   0.006074   0.004364
...         ...        ...        ...
3227 2026-03-24   0.018806  -0.000862
3228 2026-03-25  -0.010812   0.003548
3229 2026-03-26  -0.010563  -0.037594
3230 2026-03-27   0.003166   0.007888
3231 2026-03-30   0.007897   0.003793

[3232 rows x 3 columns]

In [33]:
df["Date"] = pd.to_datetime(df["Date"])
df = df.set_index("Date")

print(df.resample("QE").sum())

            Strat_Ret  Bench_Ret
Date
2013-06-30  -0.075057  -0.029621
2013-09-30   0.078549   0.054805
2013-12-31   0.103693   0.100738
2014-03-31   0.053664   0.019150
2014-06-30   0.084231   0.051673
2014-09-30  -0.042253   0.012288
2014-12-31   0.137811   0.044717
2015-03-31   0.003275   0.011652
2015-06-30  -0.022176   0.004026
2015-09-30  -0.085042  -0.061076
2015-12-31   0.068681   0.070618
2016-03-31   0.064443   0.018154
2016-06-30   0.045707   0.026479
2016-09-30   0.022155   0.038855
2016-12-31   0.041851   0.039897
2017-03-31   0.092208   0.057592
2017-06-30   0.045398   0.031239
2017-09-30   0.100634   0.044160
2017-12-31   0.057366   0.066280
2018-03-31  -0.038079  -0.003844
2018-06-30   0.076317   0.036876
2018-09-30   0.096292   0.073105
2018-12-31  -0.006424  -0.137740
2019-03-31   0.208072   0.129536
2019-06-30   0.069542   0.043209
2019-09-30   0.036372   0.020296
2019-12-31   0.102261   0.087654
2020-03-31  -0.098006  -0.177241
2020-06-30   0.140924   0.197243
2020-09-30   0.093493   0.089838
2020-12-31   0.128004   0.118209
2021-03-31   0.060854   0.064712
2021-06-30   0.199232   0.082090
2021-09-30   0.065814   0.007029
2021-12-31  -0.039153   0.107687
2022-03-31   0.287469  -0.041304
2022-06-30   0.099508  -0.165523
2022-09-30  -0.022135  -0.044878
2022-12-31   0.055417   0.080214
2023-03-31   0.024257   0.075539
2023-06-30   0.062277   0.085384
2023-09-30   0.034409  -0.031200
2023-12-31   0.062372   0.112451
2024-03-31   0.212645   0.100496
2024-06-30   0.022319   0.044547
2024-09-30   0.124122   0.059858
2024-12-31  -0.015954   0.026055
2025-03-31   0.016190  -0.040727
2025-06-30   0.079480   0.114021
2025-09-30   0.113365   0.079034
2025-12-31   0.029696   0.028590
2026-03-31   0.017504  -0.030720

In [10]:
df = pd.read_pickle('full_backtest_and_real_time.pkl')
df

            Full_Backtest  Real_Time
Date
2013-05-28       0.006071        NaN
2013-05-29      -0.013527        NaN
2013-05-30       0.006074        NaN
2013-05-31      -0.025349        NaN
2013-06-03       0.008268        NaN
...                   ...        ...
2026-03-26      -0.015293  -0.010563
2026-03-27      -0.007846   0.003166
2026-03-30       0.000555        NaN
2026-03-31       0.026060        NaN
2026-04-01       0.006358   0.007897

[3232 rows x 2 columns]

In [6]:
df[df.Date >= '2025-10-23']

           Date  Strat_Ret  Bench_Ret
3131 2025-10-23   0.022509  -0.000774
3132 2025-10-23   0.022509  -0.001243
3133 2025-10-23   0.022509  -0.003275
3134 2025-10-23   0.022509   0.004069
3135 2025-10-23   0.022509   0.002231
3136 2025-10-23   0.022509   0.005652
3137 2025-10-23   0.022509  -0.006843

In [2]:
2+2

4